### PR TITLE
use Thorntail 2.5.1.Final-redhat

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Forgot about this in the previous PR :-)

**Comment by Ladicek** [comment]
Thanks @quintesse! How does this work, BTW? This PR is merged, so the changes should be live now?

**Comment by quintesse** [comment]
It first goes through CI/CD and then end up on staging first (https://launch.prod-preview.openshift.io/), Then if everything is okay it get promoted manually to production whenever we want.

**Comment by Ladicek** [comment]
Ah, gotcha. Thanks. We'll wait then :-)

**Pull request merged**
