### PR TITLE
feat(catalog): use Thorntail 2.5.0, community and product

### LINKED ISSUE #1006: update Thorntail to 2.5.0
### Description

Thorntail has released 2.5.0 in community and as Red Hat product. This needs to be surfaced in the "Create New Application" flow.

### PR DESCRIPTION
**Pull request by Ladicek**
### Description

Move from Thorntail 2.4.0 to 2.5.0. Also add support for Thorntail community and product.

Closes #1006

### Checklist

- [x] I followed the contribution [guidelines](https://raw.githubusercontent.com/fabric8-launcher/launcher-application/master/CONTRIBUTING.md).
- [x] I created an [issue](https://github.com/fabric8-launcher/launcher-application/issues/new) and used it in the commit message.
- [x] I have built the project locally prior to submission with `mvn clean install`.
- [x] I kept a clean commit log (no unnecessary commits, no merge commits).
- [x] I am happy with my contribution.

### CODE REVIEW

**Comment by Ladicek** [comment]
I tested the changes manually somewhat, but I can't say I understand what I did. It just seems to work :-)

**Comment by gastaldi** [comment]
I'm sure you read the documentation first: https://github.com/fabric8-launcher/launcher-application/wiki/Creator%3A-Introduction-and-Contributing :wink:

**Comment by Ladicek** [comment]
Documentation? What's that? :grin: I'll check, thanks!

**Comment by Ladicek** [comment]
OK, I think I understand it a bit better now. Especially this page was useful: https://github.com/fabric8-launcher/launcher-application/wiki/Creator%3A-The-%60config%60-section

**Pull request merged**
